import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import imageLoader from '../imageLoader';
import styles from '../styles/Character.module.css'
import {Character, GetCharacterResults } from '../types';
import Navbar from '../components/navbar';
import logo from '../public/logo.png';

const Home: NextPage<{characters: Character[]}> = ({characters}) => {
  return (
    <>
    <Navbar />
    <div className={styles.container}>
      <Head>
        <title>Next With TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <hr />
      <h1 className={styles.h1}>Cartoon Characters</h1>
      {characters.map((character)=>{
        return (
          <>
            <div key={character.id} className={styles.card}>  
              <Link href={`/characters/${character.id}`}>
                <a><h2 className={styles.h1}>{character.name}</h2>
              <div className={styles.imageDiv}>

                <Image
                  className={styles.image}
                  loader={imageLoader} unoptimized
                  src={character.image}
                  alt={character.name}
                  width="200"
                  height="200"
                  layout='fixed'
                />
              </div>
              </a> 
              </Link>
              </div>
              
          </>
        );
      })}
    </div>
  </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: GetCharacterResults = await res.json();

  return {
    props:{
      characters: results,
    }
  }
}

export default Home;
